[GENERAL]
PORT = 9090
SIMILARITY_MEASURE = "cosine"
KEEP_ALIVE = "5m"

[API_KEYS]
OPENAI = "your_openai_api_key"
GROQ = "your_groq_api_key_here"
ANTHROPIC = "your_anthropic_api_key_here"
GEMINI = "your_gemini_api_key_here"

[API_ENDPOINTS]
SEARXNG = "http://localhost:8080"
OLLAMA = ""
